### ISSUE TITLE
Opening tag

### ISSUE THREAD

**Issue by JnxF** [adriacabeza/adriacabeza.github.io#1]
https://github.com/adriacabeza/adriacabeza.github.io/blob/866861894e5fc099cbdfa4f54652fa6ba1848f95/index.html#L46

Falta abrir un ```ul```sito por ahí

Ah, y faltan más epilepsia y ```<marquee>```s

**Comment by adriacabeza** [comment]
graxx, y tus deseos son órdenes #84856dd081e807300269d081991c7d3164a58eb5
